### ISSUE TITLE
GO disposition

### ISSUE THREAD

**Issue by mcavo** [mcavo/intro-videojuegos#2]
The cars drive under the floor tiles.

![captura de pantalla 2016-08-21 a las 10 47 09](https://cloud.githubusercontent.com/assets/7648908/17837564/ba44212c-678c-11e6-880e-e925cc59546f.png)

**Comment by eugis** [comment]
The cars now are over the floor. But it would be nice do it with layers.

**Comment by eugis** [comment]
Fixed
