### ISSUE TITLE
Resizing of spreets and positioning of GO

### ISSUE THREAD

**Issue by mcavo** [mcavo/intro-videojuegos#3]
Can we resize the PNG files from Unity or we need to create them again? Whats the ideal size?

How can we show them in the place we want?

**Comment by eugis** [comment]
Now, it's fix de position with a proportional constatn: 0.35. 
What other mechanism we could use?

**Comment by eugis** [comment]
The problem is not to resize files, we have to move the camera. 
The factor should be 0.36, which is the size of the assets
